services:
  vite:
    container_name: vite
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL?Variable not set}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
